
import cnf, auth, com



auth.run()


print("\nSE HA PRODUCIDO UN ERROR INESPERADO\n")
